// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nexus3/agent/v1/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Exec_FullMethodName          = "/nexus3.agent.v1.AgentService/Exec"
	AgentService_Signal_FullMethodName        = "/nexus3.agent.v1.AgentService/Signal"
	AgentService_SessionStatus_FullMethodName = "/nexus3.agent.v1.AgentService/SessionStatus"
	AgentService_ListSessions_FullMethodName  = "/nexus3.agent.v1.AgentService/ListSessions"
	AgentService_Copy_FullMethodName          = "/nexus3.agent.v1.AgentService/Copy"
	AgentService_AgentInfo_FullMethodName     = "/nexus3.agent.v1.AgentService/AgentInfo"
	AgentService_RestartAgent_FullMethodName  = "/nexus3.agent.v1.AgentService/RestartAgent"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the gRPC control-plane service exposed by the in-guest PID-1
// agent on a fixed vsock port.  All RPCs are unary request/response.
//
// Interactive stdio is NOT modelled here; it flows on a separate multiplexed,
// clawk-framed vsock data connection (handshake/data/winsize/exit frames,
// ticket 36).
type AgentServiceClient interface {
	// Exec starts a process (optionally with a PTY).
	// Returns once the process is running.  Interactive stdio flows on the
	// data-plane connection — this RPC does not stream keystrokes.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error)
	// Signal delivers a POSIX signal to the process of a running session.
	Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	// SessionStatus returns read-only status for a single session.
	SessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error)
	// ListSessions returns read-only status for all known sessions.
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// Copy negotiates a file-transfer operation (split-plane, ticket 22).
	// Metadata travels on this control RPC; bytes flow on the data-plane
	// side-channel identified by the returned transfer_id.
	// The agent archives directories itself (no guest tar).
	Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error)
	// AgentInfo returns the agent's build tag for version comparison.
	AgentInfo(ctx context.Context, in *AgentInfoRequest, opts ...grpc.CallOption) (*AgentInfoResponse, error)
	// RestartAgent initiates a hot-swap of the in-guest binary via
	// syscall.Exec.  See RestartAgentRequest for the full protocol.
	// The RPC may not return a response — a connection reset means the swap
	// was initiated; the host should poll Ping then AgentInfo to confirm.
	RestartAgent(ctx context.Context, in *RestartAgentRequest, opts ...grpc.CallOption) (*RestartAgentResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (*ExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecResponse)
	err := c.cc.Invoke(ctx, AgentService_Exec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Signal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, AgentService_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SessionStatus(ctx context.Context, in *SessionStatusRequest, opts ...grpc.CallOption) (*SessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_SessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyResponse)
	err := c.cc.Invoke(ctx, AgentService_Copy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) AgentInfo(ctx context.Context, in *AgentInfoRequest, opts ...grpc.CallOption) (*AgentInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInfoResponse)
	err := c.cc.Invoke(ctx, AgentService_AgentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RestartAgent(ctx context.Context, in *RestartAgentRequest, opts ...grpc.CallOption) (*RestartAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_RestartAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the gRPC control-plane service exposed by the in-guest PID-1
// agent on a fixed vsock port.  All RPCs are unary request/response.
//
// Interactive stdio is NOT modelled here; it flows on a separate multiplexed,
// clawk-framed vsock data connection (handshake/data/winsize/exit frames,
// ticket 36).
type AgentServiceServer interface {
	// Exec starts a process (optionally with a PTY).
	// Returns once the process is running.  Interactive stdio flows on the
	// data-plane connection — this RPC does not stream keystrokes.
	Exec(context.Context, *ExecRequest) (*ExecResponse, error)
	// Signal delivers a POSIX signal to the process of a running session.
	Signal(context.Context, *SignalRequest) (*SignalResponse, error)
	// SessionStatus returns read-only status for a single session.
	SessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error)
	// ListSessions returns read-only status for all known sessions.
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// Copy negotiates a file-transfer operation (split-plane, ticket 22).
	// Metadata travels on this control RPC; bytes flow on the data-plane
	// side-channel identified by the returned transfer_id.
	// The agent archives directories itself (no guest tar).
	Copy(context.Context, *CopyRequest) (*CopyResponse, error)
	// AgentInfo returns the agent's build tag for version comparison.
	AgentInfo(context.Context, *AgentInfoRequest) (*AgentInfoResponse, error)
	// RestartAgent initiates a hot-swap of the in-guest binary via
	// syscall.Exec.  See RestartAgentRequest for the full protocol.
	// The RPC may not return a response — a connection reset means the swap
	// was initiated; the host should poll Ping then AgentInfo to confirm.
	RestartAgent(context.Context, *RestartAgentRequest) (*RestartAgentResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Exec(context.Context, *ExecRequest) (*ExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedAgentServiceServer) Signal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedAgentServiceServer) SessionStatus(context.Context, *SessionStatusRequest) (*SessionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SessionStatus not implemented")
}
func (UnimplementedAgentServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedAgentServiceServer) Copy(context.Context, *CopyRequest) (*CopyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Copy not implemented")
}
func (UnimplementedAgentServiceServer) AgentInfo(context.Context, *AgentInfoRequest) (*AgentInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AgentInfo not implemented")
}
func (UnimplementedAgentServiceServer) RestartAgent(context.Context, *RestartAgentRequest) (*RestartAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartAgent not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Exec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Exec(ctx, req.(*ExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Signal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SessionStatus(ctx, req.(*SessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Copy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Copy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Copy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Copy(ctx, req.(*CopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_AgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).AgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_AgentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).AgentInfo(ctx, req.(*AgentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RestartAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RestartAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RestartAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RestartAgent(ctx, req.(*RestartAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus3.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _AgentService_Exec_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _AgentService_Signal_Handler,
		},
		{
			MethodName: "SessionStatus",
			Handler:    _AgentService_SessionStatus_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _AgentService_ListSessions_Handler,
		},
		{
			MethodName: "Copy",
			Handler:    _AgentService_Copy_Handler,
		},
		{
			MethodName: "AgentInfo",
			Handler:    _AgentService_AgentInfo_Handler,
		},
		{
			MethodName: "RestartAgent",
			Handler:    _AgentService_RestartAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexus3/agent/v1/agent.proto",
}
