// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nexus3/agent/v1/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionState is the lifecycle state of a session as seen by the agent.
type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_RUNNING     SessionState = 1
	SessionState_SESSION_STATE_EXITED      SessionState = 2
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_RUNNING",
		2: "SESSION_STATE_EXITED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_RUNNING":     1,
		"SESSION_STATE_EXITED":      2,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus3_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_nexus3_agent_v1_agent_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

// CopyDirection controls the transfer direction.
type CopyDirection int32

const (
	CopyDirection_COPY_DIRECTION_UNSPECIFIED CopyDirection = 0
	// PUSH: host → guest (operator-initiated write into the sandbox).
	CopyDirection_COPY_DIRECTION_PUSH CopyDirection = 1
	// PULL: guest → host (extracting files from the sandbox).
	CopyDirection_COPY_DIRECTION_PULL CopyDirection = 2
)

// Enum value maps for CopyDirection.
var (
	CopyDirection_name = map[int32]string{
		0: "COPY_DIRECTION_UNSPECIFIED",
		1: "COPY_DIRECTION_PUSH",
		2: "COPY_DIRECTION_PULL",
	}
	CopyDirection_value = map[string]int32{
		"COPY_DIRECTION_UNSPECIFIED": 0,
		"COPY_DIRECTION_PUSH":        1,
		"COPY_DIRECTION_PULL":        2,
	}
)

func (x CopyDirection) Enum() *CopyDirection {
	p := new(CopyDirection)
	*p = x
	return p
}

func (x CopyDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CopyDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus3_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (CopyDirection) Type() protoreflect.EnumType {
	return &file_nexus3_agent_v1_agent_proto_enumTypes[1]
}

func (x CopyDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CopyDirection.Descriptor instead.
func (CopyDirection) EnumDescriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

// WinSize describes terminal dimensions.
// Carried as the initial PTY size inside ExecRequest.PtyOptions.
// Live resize events travel on the data-plane framed connection (clawk
// winsize frames), not via a control-plane RPC.
type WinSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	XPixels       uint32                 `protobuf:"varint,3,opt,name=x_pixels,json=xPixels,proto3" json:"x_pixels,omitempty"`
	YPixels       uint32                 `protobuf:"varint,4,opt,name=y_pixels,json=yPixels,proto3" json:"y_pixels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinSize) Reset() {
	*x = WinSize{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinSize) ProtoMessage() {}

func (x *WinSize) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinSize.ProtoReflect.Descriptor instead.
func (*WinSize) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *WinSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *WinSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *WinSize) GetXPixels() uint32 {
	if x != nil {
		return x.XPixels
	}
	return 0
}

func (x *WinSize) GetYPixels() uint32 {
	if x != nil {
		return x.YPixels
	}
	return 0
}

// PtyOptions requests a PTY for an Exec call.
type PtyOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TERM environment variable to advertise inside the PTY (e.g. "xterm-256color").
	Term string `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	// Initial terminal window size.
	InitialSize   *WinSize `protobuf:"bytes,2,opt,name=initial_size,json=initialSize,proto3" json:"initial_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyOptions) Reset() {
	*x = PtyOptions{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyOptions) ProtoMessage() {}

func (x *PtyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyOptions.ProtoReflect.Descriptor instead.
func (*PtyOptions) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PtyOptions) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *PtyOptions) GetInitialSize() *WinSize {
	if x != nil {
		return x.InitialSize
	}
	return nil
}

// ExecRequest starts a process in the guest.
//
// session_id is *host-minted* (ticket 16): the host generates and supplies it
// so that session keying is host-authoritative in the host-dials-guest model.
// Interactive stdio (stdin, stdout, stderr) flows on the data-plane framed
// connection demuxed by session_id — never through this gRPC service.
type ExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host-minted session identifier; must be unique per sandbox lifetime.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Command to execute (argv[0] is the binary, subsequent elements are args).
	Argv []string `protobuf:"bytes,2,rep,name=argv,proto3" json:"argv,omitempty"`
	// Additional environment variables to merge into the process environment.
	Env map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Working directory inside the guest (defaults to / when empty).
	Cwd string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// If set, the agent allocates a PTY for the process.
	Pty           *PtyOptions `protobuf:"bytes,5,opt,name=pty,proto3" json:"pty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ExecRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecRequest) GetPty() *PtyOptions {
	if x != nil {
		return x.Pty
	}
	return nil
}

// ExecResponse is returned once the process has been started.
type ExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Guest-side PID of the newly started process.
	Pid           int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ExecResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type SignalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session whose process should receive the signal.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// POSIX signal number (e.g. 2 = SIGINT, 9 = SIGKILL, 15 = SIGTERM).
	Signum        int32 `protobuf:"varint,2,opt,name=signum,proto3" json:"signum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *SignalRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignalRequest) GetSignum() int32 {
	if x != nil {
		return x.Signum
	}
	return 0
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

// SessionInfo carries read-only status for one session.
// It is NOT used as the reattach discriminant — reattach is the data-connection
// handshake, not a control-plane RPC (ticket 36).
type SessionInfo struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State     SessionState           `protobuf:"varint,2,opt,name=state,proto3,enum=nexus3.agent.v1.SessionState" json:"state,omitempty"`
	// Guest-side PID (0 when state is EXITED and PID has been reaped).
	Pid int32 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	// Exit code of the process; meaningful only when state == SESSION_STATE_EXITED.
	ExitCode      int32 `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *SessionInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SessionInfo) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type SessionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusRequest) Reset() {
	*x = SessionStatusRequest{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusRequest) ProtoMessage() {}

func (x *SessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusRequest.ProtoReflect.Descriptor instead.
func (*SessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *SessionStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *SessionInfo           `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStatusResponse) Reset() {
	*x = SessionStatusResponse{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStatusResponse) ProtoMessage() {}

func (x *SessionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStatusResponse.ProtoReflect.Descriptor instead.
func (*SessionStatusResponse) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SessionStatusResponse) GetInfo() *SessionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// CopyRequest negotiates a file-transfer operation.
//
// This is a *control-plane* RPC only — it carries metadata and returns a
// transfer handle.  The actual bytes flow on the data-plane side-channel
// (separate vsock connection identified by transfer_id).
// The agent archives directories itself; the caller must not run guest tar.
type CopyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Direction of the transfer.
	Direction CopyDirection `protobuf:"varint,1,opt,name=direction,proto3,enum=nexus3.agent.v1.CopyDirection" json:"direction,omitempty"`
	// Absolute path inside the guest.
	GuestPath string `protobuf:"bytes,2,opt,name=guest_path,json=guestPath,proto3" json:"guest_path,omitempty"`
	// When true the agent archives the directory tree before transfer.
	IsDirectory   bool `protobuf:"varint,3,opt,name=is_directory,json=isDirectory,proto3" json:"is_directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyRequest) Reset() {
	*x = CopyRequest{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRequest) ProtoMessage() {}

func (x *CopyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRequest.ProtoReflect.Descriptor instead.
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CopyRequest) GetDirection() CopyDirection {
	if x != nil {
		return x.Direction
	}
	return CopyDirection_COPY_DIRECTION_UNSPECIFIED
}

func (x *CopyRequest) GetGuestPath() string {
	if x != nil {
		return x.GuestPath
	}
	return ""
}

func (x *CopyRequest) GetIsDirectory() bool {
	if x != nil {
		return x.IsDirectory
	}
	return false
}

// CopyResponse carries the transfer handle the caller uses to open the
// data-plane side-channel for the actual byte transfer.
type CopyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque token identifying the data-plane transfer slot.
	TransferId    string `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyResponse) Reset() {
	*x = CopyResponse{}
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyResponse) ProtoMessage() {}

func (x *CopyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus3_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyResponse.ProtoReflect.Descriptor instead.
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return file_nexus3_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CopyResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

var File_nexus3_agent_v1_agent_proto protoreflect.FileDescriptor

const file_nexus3_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1bnexus3/agent/v1/agent.proto\x12\x0fnexus3.agent.v1\"g\n" +
	"\aWinSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x19\n" +
	"\bx_pixels\x18\x03 \x01(\rR\axPixels\x12\x19\n" +
	"\by_pixels\x18\x04 \x01(\rR\ayPixels\"]\n" +
	"\n" +
	"PtyOptions\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12;\n" +
	"\finitial_size\x18\x02 \x01(\v2\x18.nexus3.agent.v1.WinSizeR\vinitialSize\"\xf2\x01\n" +
	"\vExecRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04argv\x18\x02 \x03(\tR\x04argv\x127\n" +
	"\x03env\x18\x03 \x03(\v2%.nexus3.agent.v1.ExecRequest.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12-\n" +
	"\x03pty\x18\x05 \x01(\v2\x1b.nexus3.agent.v1.PtyOptionsR\x03pty\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\fExecResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"F\n" +
	"\rSignalRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06signum\x18\x02 \x01(\x05R\x06signum\"\x10\n" +
	"\x0eSignalResponse\"\x90\x01\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x123\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1d.nexus3.agent.v1.SessionStateR\x05state\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\"5\n" +
	"\x14SessionStatusRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"I\n" +
	"\x15SessionStatusResponse\x120\n" +
	"\x04info\x18\x01 \x01(\v2\x1c.nexus3.agent.v1.SessionInfoR\x04info\"\x15\n" +
	"\x13ListSessionsRequest\"P\n" +
	"\x14ListSessionsResponse\x128\n" +
	"\bsessions\x18\x01 \x03(\v2\x1c.nexus3.agent.v1.SessionInfoR\bsessions\"\x8d\x01\n" +
	"\vCopyRequest\x12<\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x1e.nexus3.agent.v1.CopyDirectionR\tdirection\x12\x1d\n" +
	"\n" +
	"guest_path\x18\x02 \x01(\tR\tguestPath\x12!\n" +
	"\fis_directory\x18\x03 \x01(\bR\visDirectory\"/\n" +
	"\fCopyResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId*b\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATE_RUNNING\x10\x01\x12\x18\n" +
	"\x14SESSION_STATE_EXITED\x10\x02*a\n" +
	"\rCopyDirection\x12\x1e\n" +
	"\x1aCOPY_DIRECTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13COPY_DIRECTION_PUSH\x10\x01\x12\x17\n" +
	"\x13COPY_DIRECTION_PULL\x10\x022\xa0\x03\n" +
	"\fAgentService\x12C\n" +
	"\x04Exec\x12\x1c.nexus3.agent.v1.ExecRequest\x1a\x1d.nexus3.agent.v1.ExecResponse\x12I\n" +
	"\x06Signal\x12\x1e.nexus3.agent.v1.SignalRequest\x1a\x1f.nexus3.agent.v1.SignalResponse\x12^\n" +
	"\rSessionStatus\x12%.nexus3.agent.v1.SessionStatusRequest\x1a&.nexus3.agent.v1.SessionStatusResponse\x12[\n" +
	"\fListSessions\x12$.nexus3.agent.v1.ListSessionsRequest\x1a%.nexus3.agent.v1.ListSessionsResponse\x12C\n" +
	"\x04Copy\x12\x1c.nexus3.agent.v1.CopyRequest\x1a\x1d.nexus3.agent.v1.CopyResponseBBZ@github.com/newmanchow/nexus3/internal/core/agent/agentpb;agentpbb\x06proto3"

var (
	file_nexus3_agent_v1_agent_proto_rawDescOnce sync.Once
	file_nexus3_agent_v1_agent_proto_rawDescData []byte
)

func file_nexus3_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_nexus3_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_nexus3_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus3_agent_v1_agent_proto_rawDesc), len(file_nexus3_agent_v1_agent_proto_rawDesc)))
	})
	return file_nexus3_agent_v1_agent_proto_rawDescData
}

var file_nexus3_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nexus3_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_nexus3_agent_v1_agent_proto_goTypes = []any{
	(SessionState)(0),             // 0: nexus3.agent.v1.SessionState
	(CopyDirection)(0),            // 1: nexus3.agent.v1.CopyDirection
	(*WinSize)(nil),               // 2: nexus3.agent.v1.WinSize
	(*PtyOptions)(nil),            // 3: nexus3.agent.v1.PtyOptions
	(*ExecRequest)(nil),           // 4: nexus3.agent.v1.ExecRequest
	(*ExecResponse)(nil),          // 5: nexus3.agent.v1.ExecResponse
	(*SignalRequest)(nil),         // 6: nexus3.agent.v1.SignalRequest
	(*SignalResponse)(nil),        // 7: nexus3.agent.v1.SignalResponse
	(*SessionInfo)(nil),           // 8: nexus3.agent.v1.SessionInfo
	(*SessionStatusRequest)(nil),  // 9: nexus3.agent.v1.SessionStatusRequest
	(*SessionStatusResponse)(nil), // 10: nexus3.agent.v1.SessionStatusResponse
	(*ListSessionsRequest)(nil),   // 11: nexus3.agent.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 12: nexus3.agent.v1.ListSessionsResponse
	(*CopyRequest)(nil),           // 13: nexus3.agent.v1.CopyRequest
	(*CopyResponse)(nil),          // 14: nexus3.agent.v1.CopyResponse
	nil,                           // 15: nexus3.agent.v1.ExecRequest.EnvEntry
}
var file_nexus3_agent_v1_agent_proto_depIdxs = []int32{
	2,  // 0: nexus3.agent.v1.PtyOptions.initial_size:type_name -> nexus3.agent.v1.WinSize
	15, // 1: nexus3.agent.v1.ExecRequest.env:type_name -> nexus3.agent.v1.ExecRequest.EnvEntry
	3,  // 2: nexus3.agent.v1.ExecRequest.pty:type_name -> nexus3.agent.v1.PtyOptions
	0,  // 3: nexus3.agent.v1.SessionInfo.state:type_name -> nexus3.agent.v1.SessionState
	8,  // 4: nexus3.agent.v1.SessionStatusResponse.info:type_name -> nexus3.agent.v1.SessionInfo
	8,  // 5: nexus3.agent.v1.ListSessionsResponse.sessions:type_name -> nexus3.agent.v1.SessionInfo
	1,  // 6: nexus3.agent.v1.CopyRequest.direction:type_name -> nexus3.agent.v1.CopyDirection
	4,  // 7: nexus3.agent.v1.AgentService.Exec:input_type -> nexus3.agent.v1.ExecRequest
	6,  // 8: nexus3.agent.v1.AgentService.Signal:input_type -> nexus3.agent.v1.SignalRequest
	9,  // 9: nexus3.agent.v1.AgentService.SessionStatus:input_type -> nexus3.agent.v1.SessionStatusRequest
	11, // 10: nexus3.agent.v1.AgentService.ListSessions:input_type -> nexus3.agent.v1.ListSessionsRequest
	13, // 11: nexus3.agent.v1.AgentService.Copy:input_type -> nexus3.agent.v1.CopyRequest
	5,  // 12: nexus3.agent.v1.AgentService.Exec:output_type -> nexus3.agent.v1.ExecResponse
	7,  // 13: nexus3.agent.v1.AgentService.Signal:output_type -> nexus3.agent.v1.SignalResponse
	10, // 14: nexus3.agent.v1.AgentService.SessionStatus:output_type -> nexus3.agent.v1.SessionStatusResponse
	12, // 15: nexus3.agent.v1.AgentService.ListSessions:output_type -> nexus3.agent.v1.ListSessionsResponse
	14, // 16: nexus3.agent.v1.AgentService.Copy:output_type -> nexus3.agent.v1.CopyResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_nexus3_agent_v1_agent_proto_init() }
func file_nexus3_agent_v1_agent_proto_init() {
	if File_nexus3_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus3_agent_v1_agent_proto_rawDesc), len(file_nexus3_agent_v1_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus3_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_nexus3_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_nexus3_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_nexus3_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_nexus3_agent_v1_agent_proto = out.File
	file_nexus3_agent_v1_agent_proto_goTypes = nil
	file_nexus3_agent_v1_agent_proto_depIdxs = nil
}
