package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/mdlayher/vsock"
	"golang.org/x/sys/unix"

	"github.com/newmanchow/nexus3/internal/core/agent"
	"github.com/newmanchow/nexus3/internal/core/agent/wire"
	"github.com/newmanchow/nexus3/internal/core/driver"
)

func main() {
	isPid1 := os.Getpid() == 1

	// When running as PID 1 (in-guest init), mount the standard
	// pseudo-filesystems before doing anything else.  devtmpfs populates /dev
	// (creating /dev/console, /dev/ptmx, …); proc and sysfs are expected by
	// many userspace tools.  These are raw syscall.Mount calls — they succeed
	// with a completely empty /dev directory.
	if isPid1 {
		mountGuestFS()
		// The Linux kernel provides no PATH environment variable to PID-1 (init=
		// processes). Without a default PATH, exec.Command("uname") and similar
		// relative-path exec calls fail with "executable file not found in $PATH".
		// Set a Debian/Alpine-compatible default PATH so that guest exec RPCs work
		// without callers having to use absolute paths.
		if os.Getenv("PATH") == "" {
			os.Setenv("PATH", "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
		}
	}

	// Open /dev/console for explicit diagnostic writes.  After mountGuestFS(),
	// devtmpfs has created the node.  If the open fails (e.g. non-PID-1 run),
	// diagnostic output falls back to stderr only, which the kernel connects to
	// the console when it can open /dev/console for the init process.
	con := openConsole()
	if con != nil {
		defer con.Close()
	}

	consoleLog(con, "nexus3-agent: starting (pid=%d)\n", os.Getpid())

	// When running as PID 1 (in-guest init), configure the virtio-net interface
	// with the static IP the nexus3 perimeter netstack reserves for the guest
	// (192.168.127.2/24). Static assignment — not DHCP — keeps the agent lean;
	// no DHCP client binary is required.
	if isPid1 {
		setupNetwork(con)
		// Start sshd early so the vsock bridge (startSSHForward) has a live
		// local sshd to connect to on 127.0.0.1:22.
		startSSHD(con)
	}

	ctx, cancel := signal.NotifyContext(context.Background(),
		syscall.SIGTERM, syscall.SIGINT)
	defer cancel()

	// --builder-role: run the in-guest builder lifecycle and exit immediately;
	// the normal vsock control/data-plane listeners are not needed in this mode.
	//
	// Additional --cache-disk=<device>:<mountpath> args are parsed here and
	// passed to RunBuilderRole so that ecosystem cache disks (vdd+) are mounted
	// before buildkitd starts. These args are generated by vmbuilder.guestBuild
	// from the BuilderVMSpec.CacheDisks list on the host side.
	{
		isBuilderRole := false
		var cacheDiskMounts []agent.CacheDiskMount
		for _, arg := range os.Args[1:] {
			switch {
			case arg == "--builder-role":
				isBuilderRole = true
			case strings.HasPrefix(arg, "--cache-disk="):
				pair := strings.TrimPrefix(arg, "--cache-disk=")
				parts := strings.SplitN(pair, ":", 2)
				if len(parts) == 2 && parts[0] != "" && parts[1] != "" {
					cacheDiskMounts = append(cacheDiskMounts, agent.CacheDiskMount{
						Device:    parts[0],
						MountPath: parts[1],
					})
				} else {
					consoleLog(con, "nexus3-agent: ignoring malformed --cache-disk arg: %q\n", arg)
				}
			}
		}
		if isBuilderRole {
			consoleLog(con, "nexus3-agent: builder role starting (cache disks: %d)\n", len(cacheDiskMounts))
			opts := agent.BuilderRoleOptions{CacheDisks: cacheDiskMounts}
			if err := agent.RunBuilderRole(ctx, opts); err != nil {
				consoleFatal(con, isPid1, "nexus3-agent: builder role: %v\n", err)
			}
			consoleLog(con, "nexus3-agent: builder role complete\n")
			os.Exit(0)
		}
	}

	// Bind control-plane vsock listener (port 1024).
	consoleLog(con, "nexus3-agent: vsock.Listen port %d\n", driver.AgentControlPort)
	ctrlLis, err := vsock.Listen(driver.AgentControlPort, nil)
	if err != nil {
		consoleFatal(con, isPid1, "nexus3-agent: control listener (port %d): %v\n",
			driver.AgentControlPort, err)
	}
	consoleLog(con, "nexus3-agent: control plane listening\n")

	// Bind data-plane vsock listener (port 1025).
	consoleLog(con, "nexus3-agent: vsock.Listen port %d\n", wire.DataPort)
	dataLis, err := vsock.Listen(wire.DataPort, nil)
	if err != nil {
		consoleFatal(con, isPid1, "nexus3-agent: data listener (port %d): %v\n",
			wire.DataPort, err)
	}
	consoleLog(con, "nexus3-agent: data plane listening; running agent\n")

	// Bridge vsock:22 → localhost:22 so the host can reach guest sshd via
	// nexus3 ssh --stdio without needing a TCP network interface.
	go startSSHForward(ctx, con)

	// Multiplex arbitrary host→guest TCP port forwards on vsock:3001.
	// Each connection sends a 4-byte guest TCP port then is spliced through.
	go startPortForwardMux(ctx, con)

	a := New(ctrlLis, dataLis)
	if err := a.Run(ctx); err != nil {
		consoleFatal(con, isPid1, "nexus3-agent: run: %v\n", err)
	}
	consoleLog(con, "nexus3-agent: clean shutdown\n")
}

// mountGuestFS mounts the standard pseudo-filesystems needed by Linux
// userspace.  Called only when the agent is PID 1 (in-guest init).
// Uses raw syscall.Mount — works with an entirely empty /dev.
func mountGuestFS() {
	tryMount := func(src, target, fstype string) {
		if err := syscall.Mount(src, target, fstype, 0, ""); err != nil && err != syscall.EBUSY {
			fmt.Fprintf(os.Stderr, "nexus3-agent: mount %s: %v\n", target, err)
		}
	}

	// devtmpfs populates /dev with nodes for all currently-registered kernel
	// devices (null, zero, tty, console, random, urandom, …).
	tryMount("devtmpfs", "/dev", "devtmpfs")

	// /dev/ptmx (PTY master multiplexer) may not be in devtmpfs on kernels
	// without CONFIG_UNIX98_PTYS=y; create the node explicitly so that PTY
	// sessions work.  major=5 minor=2 is the standard Linux ptmx device.
	if _, err := os.Stat("/dev/ptmx"); os.IsNotExist(err) {
		// major=5 minor=2 is the standard Linux PTY master multiplexer device.
		if err := unix.Mknod("/dev/ptmx", unix.S_IFCHR|0o666,
			int(unix.Mkdev(5, 2))); err != nil {
			fmt.Fprintf(os.Stderr, "nexus3-agent: mknod /dev/ptmx: %v\n", err)
		}
	}

	// devpts provides per-session slave PTY nodes (/dev/pts/0, …).
	// Required: opening /dev/ptmx creates a master fd and the slave is
	// accessed as /dev/pts/N (via ptsname).
	if err := os.MkdirAll("/dev/pts", 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "nexus3-agent: mkdir /dev/pts: %v\n", err)
	} else {
		tryMount("devpts", "/dev/pts", "devpts")
	}

	tryMount("proc", "/proc", "proc")
	tryMount("sys", "/sys", "sysfs")
}

// openConsole opens /dev/console write-only for explicit diagnostic output.
// Returns nil if the device cannot be opened (caller must tolerate nil).
func openConsole() *os.File {
	f, _ := os.OpenFile("/dev/console", os.O_WRONLY, 0)
	return f
}

// consoleLog writes a formatted message to con (if non-nil) and to stderr.
func consoleLog(con *os.File, format string, args ...any) {
	msg := fmt.Sprintf(format, args...)
	if con != nil {
		_, _ = fmt.Fprint(con, msg)
	}
	_, _ = fmt.Fprint(os.Stderr, msg)
}

// consoleFatal logs msg to con and stderr, sleeps 3 s so the CH serial device
// can flush the message to the host capture file, then exits.
// Does not return.
func consoleFatal(con *os.File, isPid1 bool, format string, args ...any) {
	consoleLog(con, format, args...)
	// Sleep to allow CH's serial device to flush the log entry to the host
	// file before the kernel panics (when running as PID 1) or the process
	// exits (non-PID-1 use).
	time.Sleep(3 * time.Second)
	if isPid1 {
		// Ensure any virtio ring writes are flushed before exit triggers panic.
		syscall.Sync()
	}
	os.Exit(1)
}
