package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/mdlayher/vsock"
	"golang.org/x/sys/unix"

	"github.com/newmanchow/nexus3/internal/core/agent"
	"github.com/newmanchow/nexus3/internal/core/agent/wire"
	"github.com/newmanchow/nexus3/internal/core/driver"
)

// agentBuildTag is stamped at image-build time via:
//
//	go build -ldflags "-X main.agentBuildTag=<YYYYMMDD>-<git-short-sha>"
//
// Default "dev" means the binary was built without stamping (local dev or
// direct `go build` without the Makefile / rebuild script).  When a sandbox
// starts, this tag is printed on the console so the operator can compare it
// against the current git revision to detect image staleness.  Any arg the
// agent does not recognize is also logged with this tag so the operator can
// correlate the unknown arg with the agent version that ignored it.
var agentBuildTag = "dev"

func main() {
	isPid1 := os.Getpid() == 1

	// When running as PID 1 (in-guest init), mount the standard
	// pseudo-filesystems before doing anything else.  devtmpfs populates /dev
	// (creating /dev/console, /dev/ptmx, …); proc and sysfs are expected by
	// many userspace tools.  These are raw syscall.Mount calls — they succeed
	// with a completely empty /dev directory.
	if isPid1 {
		mountGuestFS()
		// The Linux kernel provides no PATH environment variable to PID-1 (init=
		// processes). Without a default PATH, exec.Command("uname") and similar
		// relative-path exec calls fail with "executable file not found in $PATH".
		// Set a Debian/Alpine-compatible default PATH so that guest exec RPCs work
		// without callers having to use absolute paths.
		if os.Getenv("PATH") == "" {
			os.Setenv("PATH", "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
		}
	}

	// Open /dev/console for explicit diagnostic writes.  After mountGuestFS(),
	// devtmpfs has created the node.  If the open fails (e.g. non-PID-1 run),
	// diagnostic output falls back to stderr only, which the kernel connects to
	// the console when it can open /dev/console for the init process.
	con := openConsole()
	if con != nil {
		defer con.Close()
	}

	consoleLog(con, "nexus3-agent: starting (pid=%d build=%s)\n", os.Getpid(), agentBuildTag)
	if isPid1 {
		// /tmp is unconditionally RAM-backed: 32 MiB seed; resizer grows it to
		// max(1 GiB, min(50%% MemTotal, 2 GiB)). The 1 GiB floor prevents scratch
		// starvation on small sandboxes — tmpfs is sized, not preallocated, so
		// a 1 GiB floor on a 512 MiB guest costs nothing until written.
		consoleLog(con, "nexus3-agent: /tmp: RAM-backed tmpfs (32 MiB seed; resizer target = max(1 GiB, min(50%%%% MemTotal, 2 GiB)))\n")
	}

	// When running as PID 1 (in-guest init), configure the virtio-net interface
	// with the static IP the nexus3 perimeter netstack reserves for the guest
	// (192.168.127.2/24). Static assignment — not DHCP — keeps the agent lean;
	// no DHCP client binary is required.
	if isPid1 {
		setupNetwork(con)
		// Start sshd early so the vsock bridge (startSSHForward) has a live
		// local sshd to connect to on 127.0.0.1:22.
		startSSHD(con)
	}

	ctx, cancel := signal.NotifyContext(context.Background(),
		syscall.SIGTERM, syscall.SIGINT)
	defer cancel()

	// Parse all kernel cmdline / exec args before branching on role.
	//
	// --builder-role:                    exec builder lifecycle and exit.
	// --cache-disk=<device>:<mountpath>: cache disk mounts for builder role.
	// --workspace-mount=<device>:<target>:<fstype>:<readonly>:
	//                                    workspace/shadow disk mounts for normal
	//                                    agent mode; generated by the host's
	//                                    workspaceMountCmdline helper and passed
	//                                    via the Linux kernel cmdline after "--",
	//                                    which delivers them as os.Args[1:] to PID 1.
	// --mem-ceiling=<bytes>:             boot-time RAM ceiling in bytes (TBD-DC-9,
	//                                    seam B — kernel cmdline). The host (AR-DRV /
	//                                    AR-CLI) must emit this alongside workspace mounts.
	//                                    Used by the governor; /tmp resize uses live MemTotal.
	var wsMounts []agent.GuestMount
	var memCeilingBytes int64
	var sandboxHandle string // set from --sandbox-handle=<handle> on the kernel cmdline
	{
		isBuilderRole := false
		var cacheDiskMounts []agent.CacheDiskMount
		for _, arg := range os.Args[1:] {
			switch {
			case arg == "--builder-role":
				isBuilderRole = true
			case strings.HasPrefix(arg, "--mem-ceiling="):
				v := strings.TrimPrefix(arg, "--mem-ceiling=")
				if n, err := strconv.ParseInt(v, 10, 64); err == nil {
					memCeilingBytes = n
				} else {
					consoleLog(con, "nexus3-agent: ignoring malformed --mem-ceiling arg: %q\n", arg)
				}
			case strings.HasPrefix(arg, "--cache-disk="):
				pair := strings.TrimPrefix(arg, "--cache-disk=")
				parts := strings.SplitN(pair, ":", 2)
				if len(parts) == 2 && parts[0] != "" && parts[1] != "" {
					cacheDiskMounts = append(cacheDiskMounts, agent.CacheDiskMount{
						Device:    parts[0],
						MountPath: parts[1],
					})
				} else {
					consoleLog(con, "nexus3-agent: ignoring malformed --cache-disk arg: %q\n", arg)
				}
			case strings.HasPrefix(arg, "--sandbox-handle="):
				sandboxHandle = strings.TrimPrefix(arg, "--sandbox-handle=")
			case strings.HasPrefix(arg, "--workspace-mount="):
				m, ok := parseWorkspaceMountArg(arg)
				if ok {
					wsMounts = append(wsMounts, m)
				} else {
					consoleLog(con, "nexus3-agent: ignoring malformed --workspace-mount arg: %q\n", arg)
				}
			default:
				// An unrecognized arg most likely means the host is newer than the
				// guest agent: the host emits a flag this agent version does not
				// understand. Log it loudly rather than silently ignoring it so
				// the operator can see the skew in the serial/console capture and
				// know to rebuild the base image.  We continue rather than fataling
				// because PID-1 exit triggers a kernel panic; a loud degraded mode
				// is safer and still gives the operator the information they need.
				consoleLog(con, "nexus3-agent: WARN: unrecognized cmdline arg %q — host/guest version skew? agent build=%s\n", arg, agentBuildTag)
			}
		}
		if isBuilderRole {
			consoleLog(con, "nexus3-agent: builder role starting (cache disks: %d)\n", len(cacheDiskMounts))
			opts := agent.BuilderRoleOptions{CacheDisks: cacheDiskMounts}
			if err := agent.RunBuilderRole(ctx, opts); err != nil {
				consoleFatal(con, isPid1, "nexus3-agent: builder role: %v\n", err)
			}
			consoleLog(con, "nexus3-agent: builder role complete\n")
			os.Exit(0)
		}
	}

	// Set the guest hostname. When --sandbox-handle= was supplied on the kernel
	// cmdline the sandbox's human-readable handle becomes the hostname so that
	// the shell prompt reads "root@<handle>:/#" instead of "root@(none):/#".
	// Absent the arg (old host or plain VM launch) we fall back to "nexus3" —
	// always better than the kernel's default "(none)".
	// This is best-effort; failure is logged but never fatal (PID-1 exit = panic).
	if isPid1 {
		hn := sandboxHandle
		if hn == "" {
			hn = "nexus3"
		}
		if err := syscall.Sethostname([]byte(hn)); err != nil {
			consoleLog(con, "nexus3-agent: sethostname(%q): %v\n", hn, err)
		} else {
			consoleLog(con, "nexus3-agent: hostname=%q\n", hn)
		}
	}

	// Mount workspace and shadow disks when --workspace-mount= args were
	// supplied in the kernel cmdline. This must happen before the vsock
	// listeners start so no workload can access the workspace path before
	// the disks are visible. Failure is fatal: a sandbox with unmounted
	// workspace disks is the failure mode we are eliminating.
	if len(wsMounts) > 0 {
		consoleLog(con, "nexus3-agent: mounting workspace (%d mounts)\n", len(wsMounts))
		if err := agent.MountWorkspace(wsMounts); err != nil {
			consoleFatal(con, isPid1, "nexus3-agent: workspace mount failed: %v\n", err)
		}
		consoleLog(con, "nexus3-agent: workspace mounts complete\n")
	}

	// Derive the workspace mount path for disk telemetry (statfs). The workspace
	// mount is identified by GuestMount.IsWorkspace=true — an explicit marker set
	// by WorkspaceGuestMount on the host side. Shadow mounts always have IsWorkspace=false,
	// so position-based or ReadOnly-based inference is never used here.
	workspacePath := ""
	if wsMount, ok, err := selectWorkspaceMount(wsMounts); err != nil {
		consoleFatal(con, isPid1, "nexus3-agent: workspace mount selection: %v\n", err)
	} else if ok {
		workspacePath = wsMount.Target
	} else {
		// No mount claimed IsWorkspace. The likeliest cause is host/guest version
		// skew: an older host emits the 4-field mount spec, which parses as
		// IsWorkspace=false for every mount. Disk telemetry then reports nothing
		// and the disk governor never grows — degrade loudly rather than silently.
		consoleLog(con, "nexus3-agent: auto-resize: NO workspace mount found in %d mount(s); disk telemetry disabled (host may predate the 5-field mount spec)\n", len(wsMounts))
	}

	// Wire in auto-resize services: ZRAM swap safety net, telemetry server on
	// vsock:3002, vCPU onliner, and /tmp tmpfs resizer. Now unconditional —
	// being PID 1 is sufficient; the --auto-resize opt-in token has been removed.
	// ZRAM runs synchronously inside startResizeServices before returning so it
	// is active before the vsock listeners open and any workload can start
	// (spec-08:67,231 MUST).
	consoleLog(con, "nexus3-agent: auto-resize: starting services (mem-ceiling=%d)\n", memCeilingBytes)
	startResizeServices(ctx, con, workspacePath, memCeilingBytes)

	// Bind control-plane vsock listener (port 1024).
	consoleLog(con, "nexus3-agent: vsock.Listen port %d\n", driver.AgentControlPort)
	ctrlLis, err := vsock.Listen(driver.AgentControlPort, nil)
	if err != nil {
		consoleFatal(con, isPid1, "nexus3-agent: control listener (port %d): %v\n",
			driver.AgentControlPort, err)
	}
	consoleLog(con, "nexus3-agent: control plane listening\n")

	// Bind data-plane vsock listener (port 1025).
	consoleLog(con, "nexus3-agent: vsock.Listen port %d\n", wire.DataPort)
	dataLis, err := vsock.Listen(wire.DataPort, nil)
	if err != nil {
		consoleFatal(con, isPid1, "nexus3-agent: data listener (port %d): %v\n",
			wire.DataPort, err)
	}
	consoleLog(con, "nexus3-agent: data plane listening; running agent\n")

	// Bridge vsock:22 → localhost:22 so the host can reach guest sshd via
	// nexus3 ssh --stdio without needing a TCP network interface.
	go startSSHForward(ctx, con)

	// Multiplex arbitrary host→guest TCP port forwards on vsock:3001.
	// Each connection sends a 4-byte guest TCP port then is spliced through.
	go startPortForwardMux(ctx, con)

	a := New(ctrlLis, dataLis)
	if err := a.Run(ctx); err != nil {
		consoleFatal(con, isPid1, "nexus3-agent: run: %v\n", err)
	}
	consoleLog(con, "nexus3-agent: clean shutdown\n")
}

// guestMountFn is the syscall used by mountGuestFS. Replaced in tests to
// capture mount calls without requiring root or a real mount namespace.
var guestMountFn = func(source, target, fstype string, flags uintptr, data string) error {
	return syscall.Mount(source, target, fstype, flags, data)
}

// mountGuestFS mounts the standard pseudo-filesystems needed by Linux
// userspace.  Called only when the agent is PID 1 (in-guest init).
// Uses raw syscall.Mount — works with an entirely empty /dev.
//
// /tmp is unconditionally mounted as a 32 MiB tmpfs seed so the /tmp resizer
// (startTmpfsResizer) can grow it to max(1 GiB, min(50% MemTotal, 2 GiB)).
// The seed of 32 MiB is always smaller than the 1 GiB floor, so the first
// resizer tick always fires and replaces the seed with the real target.
// tmpfs is sized, not preallocated — a 1 GiB ceiling on a 512 MiB guest costs
// nothing until bytes are actually written.
func mountGuestFS() {
	tryMount := func(src, target, fstype, data string) {
		if err := guestMountFn(src, target, fstype, 0, data); err != nil && err != syscall.EBUSY {
			fmt.Fprintf(os.Stderr, "nexus3-agent: mount %s: %v\n", target, err)
		}
	}

	// devtmpfs populates /dev with nodes for all currently-registered kernel
	// devices (null, zero, tty, console, random, urandom, …).
	tryMount("devtmpfs", "/dev", "devtmpfs", "")

	// /dev/ptmx (PTY master multiplexer) may not be in devtmpfs on kernels
	// without CONFIG_UNIX98_PTYS=y; create the node explicitly so that PTY
	// sessions work.  major=5 minor=2 is the standard Linux ptmx device.
	if _, err := os.Stat("/dev/ptmx"); os.IsNotExist(err) {
		// major=5 minor=2 is the standard Linux PTY master multiplexer device.
		if err := unix.Mknod("/dev/ptmx", unix.S_IFCHR|0o666,
			int(unix.Mkdev(5, 2))); err != nil {
			fmt.Fprintf(os.Stderr, "nexus3-agent: mknod /dev/ptmx: %v\n", err)
		}
	}

	// devpts provides per-session slave PTY nodes (/dev/pts/0, …).
	// Required: opening /dev/ptmx creates a master fd and the slave is
	// accessed as /dev/pts/N (via ptsname).
	if err := os.MkdirAll("/dev/pts", 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "nexus3-agent: mkdir /dev/pts: %v\n", err)
	} else {
		tryMount("devpts", "/dev/pts", "devpts", "")
	}

	tryMount("proc", "/proc", "proc", "")
	tryMount("sys", "/sys", "sysfs", "")

	// cgroupv2 unified hierarchy — required by containerd/dockerd running
	// inside the sandbox. Must be mounted after /sys.
	if err := os.MkdirAll("/sys/fs/cgroup", 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "nexus3-agent: mkdir /sys/fs/cgroup: %v\n", err)
	} else {
		tryMount("cgroup2", "/sys/fs/cgroup", "cgroup2", "")
	}

	// tmpfs on /tmp — required for the /tmp auto-resizer (resize_tmp_linux.go).
	// Initial size: 32 MiB (always less than the 1 GiB floor the resizer targets,
	// so the first resizer tick always fires and grows /tmp to
	// max(1 GiB, min(50% MemTotal, 2 GiB)) before the vsock listeners open).
	// Using size=0 (unlimited) would give f_blocks=ULONG_MAX, making
	// currentTmpCapBytes() enormous and the resizer would never grow it.
	//
	// Ported from OLD packages/nexus/cmd/nexus-guest-agent/tmp_resize.go.
	tryMount("tmpfs", "/tmp", "tmpfs", "size=32m")
}

// openConsole opens /dev/console write-only for explicit diagnostic output.
// Returns nil if the device cannot be opened (caller must tolerate nil).
func openConsole() *os.File {
	f, _ := os.OpenFile("/dev/console", os.O_WRONLY, 0)
	return f
}

// consoleLog writes a formatted message to con (if non-nil) and to stderr.
func consoleLog(con *os.File, format string, args ...any) {
	msg := fmt.Sprintf(format, args...)
	if con != nil {
		_, _ = fmt.Fprint(con, msg)
	}
	_, _ = fmt.Fprint(os.Stderr, msg)
}

// consoleFatal logs msg to con and stderr, sleeps 3 s so the CH serial device
// can flush the message to the host capture file, then exits.
// Does not return.
func consoleFatal(con *os.File, isPid1 bool, format string, args ...any) {
	consoleLog(con, format, args...)
	// Sleep to allow CH's serial device to flush the log entry to the host
	// file before the kernel panics (when running as PID 1) or the process
	// exits (non-PID-1 use).
	time.Sleep(3 * time.Second)
	if isPid1 {
		// Ensure any virtio ring writes are flushed before exit triggers panic.
		syscall.Sync()
	}
	os.Exit(1)
}
