package main

import (
	"strings"

	"github.com/newmanchow/nexus3/internal/core/agent"
)

// parseWorkspaceMountArg parses a single "--workspace-mount=<device>:<target>:<fstype>:<readonly>"
// kernel cmdline argument (generated by workspaceMountCmdline on the host side).
//
// Format: --workspace-mount=/dev/vdb:/workspace/repo:ext4:false
//   - device:   guest block device path (e.g. "/dev/vdb")
//   - target:   absolute mount-point inside the VM (e.g. "/workspace/repo")
//   - fstype:   filesystem type (e.g. "ext4")
//   - readonly: "true" → MS_RDONLY; anything else → read-write
//
// Returns the parsed GuestMount and true on success. Returns a zero value and
// false when the arg is absent, missing the prefix, or has fewer than 4 colon-
// separated fields.
func parseWorkspaceMountArg(arg string) (agent.GuestMount, bool) {
	const prefix = "--workspace-mount="
	if !strings.HasPrefix(arg, prefix) {
		return agent.GuestMount{}, false
	}
	pair := strings.TrimPrefix(arg, prefix)
	// SplitN with n=4: device, target, fstype, readonly — last field keeps any
	// colons that might appear in it (none expected for "true"/"false", but
	// defensive).
	parts := strings.SplitN(pair, ":", 4)
	if len(parts) != 4 || parts[0] == "" || parts[1] == "" || parts[2] == "" {
		return agent.GuestMount{}, false
	}
	return agent.GuestMount{
		Device:   parts[0],
		Target:   parts[1],
		FSType:   parts[2],
		ReadOnly: parts[3] == "true",
	}, true
}
