package main

import (
	"fmt"
	"strings"

	"github.com/IniZio/nexus3/internal/core/agent"
)

// parseWorkspaceMountArg parses a single "--workspace-mount=<device>:<target>:<fstype>:<readonly>:<workspace>:<resizable>"
//
// Cross-version skew hazard: SplitN(n=6) caps splitting at 6 pieces.
// If a future host adds a 7th field, it is absorbed into parts[5] as
// "true:<newfield>", breaking Resizable silently. ReadOnly (parts[3]) and
// IsWorkspace (parts[4]) are safe under this scenario because SplitN stops
// before absorbing them. Any future format addition MUST bump n and update
// field indices here to maintain cross-version correctness.
// kernel cmdline argument (generated by workspaceMountCmdline on the host side).
//
// Format: --workspace-mount=/dev/vdf:/workspace/repo:ext4:false:true:false
//         --workspace-mount=/dev/vdb:/var/lib/docker:ext4:false:false:true
//         --workspace-mount=workspace-tag:/workspace/repo:virtiofs:false:true:false
//   - device:    mount source; interpretation depends on fstype:
//                ext4 → guest block device path (e.g. "/dev/vdb");
//                virtiofs (D-PD-53) → virtiofs tag string (e.g. "workspace-tag"), not a /dev path
//   - target:    absolute mount-point inside the VM (e.g. "/workspace/repo")
//   - fstype:    filesystem type (e.g. "ext4")
//   - readonly:  "true" → MS_RDONLY; anything else → read-write
//   - workspace: "true" → this is the primary workspace disk (telemetry target);
//     absent or anything else → shadow disk (IsWorkspace=false)
//   - resizable: "true" → non-workspace ext4 disk managed by the governor (e.g.
//     /var/lib/docker named-volume disk); absent or anything else → false
//
// The 5th field (workspace) is optional for backward compatibility: a 4-field
// arg (old format) is accepted and yields IsWorkspace=false.
// The 6th field (resizable) is optional: a 5-field arg yields Resizable=false.
//
// Returns the parsed GuestMount and true on success. Returns a zero value and
// false when the arg is absent, missing the prefix, or has fewer than 4 colon-
// separated fields.
func parseWorkspaceMountArg(arg string) (agent.GuestMount, bool) {
	const prefix = "--workspace-mount="
	if !strings.HasPrefix(arg, prefix) {
		return agent.GuestMount{}, false
	}
	pair := strings.TrimPrefix(arg, prefix)
	// SplitN with n=6: device, target, fstype, readonly, workspace, resizable.
	// Fields 5 and 6 are optional; old (4- or 5-field) formats are accepted.
	parts := strings.SplitN(pair, ":", 6)
	if len(parts) < 4 || parts[0] == "" || parts[1] == "" || parts[2] == "" {
		return agent.GuestMount{}, false
	}
	isWorkspace := false
	if len(parts) >= 5 {
		isWorkspace = parts[4] == "true"
	}
	isResizable := false
	if len(parts) == 6 {
		isResizable = parts[5] == "true"
	}
	return agent.GuestMount{
		Device:      parts[0],
		Target:      parts[1],
		FSType:      parts[2],
		ReadOnly:    parts[3] == "true",
		IsWorkspace: isWorkspace,
		Resizable:   isResizable,
	}, true
}

// selectWorkspaceMount returns the single mount in mounts that has IsWorkspace=true.
//
// Returns (mount, true, nil) when exactly one workspace mount is found.
// Returns (zero, false, nil) when no workspace mount is present — callers treat
// this as "disk telemetry unavailable", not a fatal error.
// Returns (zero, false, error) when more than one workspace mount is found —
// this indicates a misconfiguration on the host side and must be treated as a
// bug, not silently resolved by picking the first.
func selectWorkspaceMount(mounts []agent.GuestMount) (agent.GuestMount, bool, error) {
	var found agent.GuestMount
	count := 0
	for _, m := range mounts {
		if m.IsWorkspace {
			found = m
			count++
		}
	}
	switch count {
	case 0:
		return agent.GuestMount{}, false, nil
	case 1:
		return found, true, nil
	default:
		return agent.GuestMount{}, false, fmt.Errorf("selectWorkspaceMount: %d mounts have IsWorkspace=true; exactly one is required", count)
	}
}
