// Package selfhost — nested-boot image builder.
//
// BuildNestedBootImage produces the outer VM image used by the T5 nested-boot
// integration proof (nested_boot_test.go). It is a test helper, not production
// code: it lives in the selfhost package alongside the other baseimage helpers.
package selfhost

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"

	"github.com/newmanchow/nexus3/internal/core/builder"
	"github.com/newmanchow/nexus3/internal/core/domain"
	"github.com/newmanchow/nexus3/internal/core/image"
)

const (
	// nestedDockerTag is the temporary docker image tag used during build.
	// It is removed (docker rmi --force) immediately after the rootfs export.
	nestedDockerTag = "nexus3-nested-boot-test:dev"

	// nestedImageSizeBytes is the ext4 image size for the outer nested-boot VM image.
	// The rootfs is minimal (~250 MiB max): ubuntu:24.04 base + cloud-hypervisor
	// static binary + vmlinux kernel + nexus3-agent. 1 GiB gives ample headroom.
	nestedImageSizeBytes = 1 << 30 // 1 GiB
)

// nestedBootContainerfile is the Dockerfile for the outer nested-boot VM image.
//
// It is a test fixture: it produces an image that contains:
//   - cloud-hypervisor static binary at /usr/local/bin/cloud-hypervisor
//   - the inner-VM kernel at /boot/vmlinux (staged from the build context)
//   - nexus3-agent at /sbin/nexus3-agent (boot contract: init=/sbin/nexus3-agent)
//
// The build context (prepared by BuildNestedBootImage) must contain:
//   - vmlinux       (inner-VM kernel; vmlinux-x86_64 renamed for brevity)
//   - nexus3-agent  (guest agent binary compiled from cmd/nexus3-agent)
//
// This Containerfile is intentionally NOT the repo-root .nexus/Containerfile —
// that file is the production outer-image recipe and must not be mutated by T5.
const nestedBootContainerfile = `# T5 test fixture — nested-boot outer VM image.
# Generated by internal/test/selfhost/baseimage_nested.go; do not edit manually.
#
# Purpose: prove that cloud-hypervisor NestedVirt=true (T4) exposes /dev/kvm
# inside the outer guest and that an inner VM can be launched from there.
#
# Build context (provided by BuildNestedBootImage):
#   vmlinux       — inner-VM kernel (images/kernel/vmlinux-x86_64)
#   nexus3-agent  — guest PID-1 agent binary

FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
    && rm -rf /var/lib/apt/lists/*

# ── cloud-hypervisor static binary ──────────────────────────────────────────
# Download the latest stable release from GitHub. The outer guest uses this
# binary to launch the INNER VM (the nested-boot proof).
RUN curl -fsSL \
        "https://github.com/cloud-hypervisor/cloud-hypervisor/releases/latest/download/cloud-hypervisor-static" \
        -o /usr/local/bin/cloud-hypervisor \
    && chmod +x /usr/local/bin/cloud-hypervisor \
    && cloud-hypervisor --version

# ── Inner-VM kernel ──────────────────────────────────────────────────────────
# Staged from the build context (images/kernel/vmlinux-x86_64 on the host).
# The T3 build-context mechanism (WorkspaceDir → build context) is mirrored
# here: the file is explicitly copied into the docker build context by
# BuildNestedBootImage before docker build is invoked.
COPY vmlinux /boot/vmlinux

# ── Guest agent ──────────────────────────────────────────────────────────────
# Boot contract: root=/dev/vda rw init=/sbin/nexus3-agent console=ttyS0
COPY nexus3-agent /sbin/nexus3-agent
RUN chmod 0755 /sbin/nexus3-agent
`

// BuildNestedBootImage produces the outer nested-boot ext4 image and stores it
// in cache keyed by SHA-256 digest.
//
// The image extends ubuntu:24.04 with:
//   - cloud-hypervisor (latest stable static binary from GitHub)
//   - inner-VM kernel at /boot/vmlinux (staged from images/kernel/vmlinux-x86_64)
//   - nexus3-agent at /sbin/nexus3-agent (boot contract: init=/sbin/nexus3-agent)
//
// Prerequisite checks:
//   - docker in PATH (returns [ErrDockerUnavailable] if absent)
//   - mke2fs in PATH (returns [builder.ErrMke2fsUnavailable] if absent)
//   - images/kernel/vmlinux-x86_64 present in the repo root
//
// Build steps:
//  1. Compile cmd/nexus3-agent CGO_ENABLED=0 GOOS=linux GOARCH=amd64.
//  2. Copy vmlinux-x86_64 kernel into the docker build context as "vmlinux".
//  3. docker build with [nestedBootContainerfile] (installs cloud-hypervisor,
//     stages kernel and agent binary).
//  4. docker create → docker export → extract tar → rootfs tree.
//  5. mke2fs -d <rootfs> with deterministic flags → raw ext4 (1 GiB).
//  6. SHA-256 hash → cache.Put → return domain.Image.
func BuildNestedBootImage(ctx context.Context, cache *image.Cache) (domain.Image, error) {
	// ── Prerequisite checks ───────────────────────────────────────────────────

	if _, err := exec.LookPath("docker"); err != nil {
		return domain.Image{}, ErrDockerUnavailable
	}
	if !builder.Mke2fsAvailable() {
		return domain.Image{}, builder.ErrMke2fsUnavailable
	}

	// ── Locate repo root ──────────────────────────────────────────────────────

	repoRoot, err := findRepoRoot()
	if err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: find repo root: %w", err)
	}

	// ── Verify kernel exists before starting a long build ────────────────────

	kernelSrc := filepath.Join(repoRoot, "images", "kernel", "vmlinux-x86_64")
	if _, err := os.Stat(kernelSrc); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: kernel not found at %s: %w", kernelSrc, err)
	}

	// ── Working directory ─────────────────────────────────────────────────────

	workDir, err := os.MkdirTemp("", "nexus3-nested-image-*")
	if err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: mkdir work: %w", err)
	}
	defer os.RemoveAll(workDir)

	// ── Step 1: build nexus3-agent static binary ──────────────────────────────

	agentBin := filepath.Join(workDir, "nexus3-agent")
	if err := buildAgent(ctx, repoRoot, agentBin); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: build agent: %w", err)
	}

	// ── Step 2: set up docker build context ───────────────────────────────────

	ctxDir := filepath.Join(workDir, "ctx")
	if err := os.MkdirAll(ctxDir, 0o755); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: mkdir ctx: %w", err)
	}

	// Write Containerfile into context.
	cfPath := filepath.Join(ctxDir, "Containerfile")
	if err := os.WriteFile(cfPath, []byte(nestedBootContainerfile), 0o644); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: write Containerfile: %w", err)
	}

	// Copy nexus3-agent binary into context.
	if err := copyFile(agentBin, filepath.Join(ctxDir, "nexus3-agent"), 0o755); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: copy agent into ctx: %w", err)
	}

	// Copy kernel into context as "vmlinux" (mirrors T3 build-context wire).
	// vmlinux-x86_64 is the inner-VM kernel; renamed to "vmlinux" to match
	// the COPY instruction in nestedBootContainerfile.
	if err := copyFile(kernelSrc, filepath.Join(ctxDir, "vmlinux"), 0o644); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: copy kernel into ctx: %w", err)
	}

	// ── Step 3: docker build ──────────────────────────────────────────────────

	buildCmd := exec.CommandContext(ctx, "docker", "build",
		"-f", cfPath,
		"-t", nestedDockerTag,
		ctxDir,
	)
	buildCmd.Stdout = os.Stderr // progress visible in test -v output
	buildCmd.Stderr = os.Stderr
	if err := buildCmd.Run(); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: docker build: %w", err)
	}
	defer func() { _ = exec.Command("docker", "rmi", "--force", nestedDockerTag).Run() }()

	// ── Step 4: docker create → docker export → extract tar ──────────────────

	rootfsDir := filepath.Join(workDir, "rootfs")
	if err := os.MkdirAll(rootfsDir, 0o755); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: mkdir rootfs: %w", err)
	}
	if err := exportRootfs(ctx, nestedDockerTag, rootfsDir); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: export rootfs: %w", err)
	}

	// ── Step 5: mke2fs ────────────────────────────────────────────────────────

	ext4Path := filepath.Join(workDir, "nested-boot.ext4")
	if err := runMke2fs(ctx, rootfsDir, ext4Path, nestedImageSizeBytes); err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: mke2fs: %w", err)
	}

	// ── Step 6: hash and store ────────────────────────────────────────────────

	img, err := hashAndStore(ctx, cache, ext4Path)
	if err != nil {
		return domain.Image{}, fmt.Errorf("nested-image: cache store: %w", err)
	}
	return img, nil
}
